services:
  client:
    image: oven/bun:alpine
    container_name: client
    working_dir: /app
    volumes:
      - ./website:/app
    command: ["sh", "-c", "bun install && bun run dev --host"]
    ports:
      - "5173:5173"
    depends_on:
      - server
  server:
    image: oven/bun:alpine
    container_name: server
    working_dir: /app
    volumes:
      - ./server:/app
    command: ["sh", "-c", "bun install && bun run dev --host"]
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tournament_report
    depends_on:
      - db
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tournament_report
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: